server:
  servlet:
    context-path: /collector/v1
spring:
  application:
    name: collector
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mariadb://localhost:3306/collector
  jpa:
    properties:
      hibernate:
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
application:
  jwt:
    access:
      public-key: classpath:keys/access-token-public.pem
      private-key: classpath:keys/access-token-private.pem
    refresh:
      public-key: classpath:keys/refresh-token-public.pem
      private-key: classpath:keys/refresh-token-private.pem
logging:
  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis.cache: DEBUG