server:
  servlet:
    context-path: /collector/v1
spring:
  application:
    name: collector
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mariadb://localhost:3306/collector