spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/collector
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
jwt:
  private-key: classpath:app.key
  public-key: classpath:app.pub